start1= input(" Emoticon Maze start? ")
print("Made with Megatext") ## Feel Free to remove this! I understand the pain of watermarks and other marketting things!
## Input Code Here
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)              o(*^＠^*)oo(*^＠^*)oo(*^＠^*)o")
print("|")
print("|  (●'◡'●)               o(*^＠^*)o      (～￣▽￣)～")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               (┬┬﹏┬┬) ╰(*°▽°*)╯")
print("|")
print("|  (●'◡'●)              o(*^＠^*)oo(*^＠^*)oo(*^＠^*)o")
print("|")
print("|  (●'◡'●)               o(*^＠^*)o      (～￣▽￣)～")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               ☆*: .｡. o(≧▽≦)o .｡.:*☆")
print("|")
print("|  (●'◡'●)               (┬┬﹏┬┬) ╰(*°▽°*)╯")

## Ending Sequence
end1= input("Art made by WilloDude")
print("Made with Megatext") ## Feel Free to remove this! I understand the pain of watermarks and other marketting things!
end2= input("... ") ## This is to stop the file from automatically closing in the python console